In [3]:
import numpy as np

In [2]:
l= [1,2,3,4]

In [5]:
ar = np.array(l)

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
# using asarray
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
b = np.matrix(l)

In [13]:
type(b)

numpy.matrix

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

# Copying numpy array

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a # Shallow Copy

In [19]:
c[0] = 100

In [20]:
a

array([100,   2,   3,   4])

In [27]:
d = np.copy(a) # copying at new location deep copy

In [28]:
d[0] = 400

In [29]:
d

array([400,   2,   3,   4])

In [30]:
a

array([100,   2,   3,   4])

# Different numpy function

## From function

In [40]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
iterable = (i*i for i in range(5))

In [42]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [43]:
l= [1,2,3,4,5,6]
ar = np.array(l)

In [44]:
ar.ndim

1

In [49]:
np.array([[1,2],[3,4]]).ndim

2

In [50]:
np.array([[1,2],[3,4]]).size

4

In [51]:
np.array([[1,2],[3,4]]).shape

(2, 2)

In [55]:
np.array([[1,2],[3,4]]).dtype

dtype('int32')

# Range in Numpy

In [58]:
np.arange(2.4,5.6,0.1)

array([2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [60]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# numpy zeros

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# Produce onces array

In [70]:
x = np.ones(4)

In [71]:
x+5

array([6., 6., 6., 6.])

In [73]:
np.empty((3,4))

array([[4.67296746e-307, 1.69121096e-306, 1.86921822e-306,
        1.33511018e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        1.60219985e-306],
       [6.89804132e-307, 1.11261162e-306, 8.34443015e-308,
        3.91792476e-317]])

# identity matrix

In [76]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy log space

In [79]:
np.logspace(2,3,20,base=2)

array([4.        , 4.14862018, 4.30276234, 4.46263167, 4.62844095,
       4.80041088, 4.97877036, 5.16375679, 5.3556164 , 5.55460457,
       5.76098615, 5.97503585, 6.19703857, 6.42728981, 6.66609605,
       6.91377515, 7.17065677, 7.43708284, 7.71340798, 8.        ])

# Numpy random

In [83]:
arr= np.random.randn(2,4) # Mean zero, STD 1

In [84]:
import pandas as pd

In [85]:
pd.DataFrame(arr)

0         1         2         3
0  0.171095 -1.229117  0.686884  0.629707
1 -0.286553 -1.230757 -0.195671  0.815882

In [87]:
np.random.rand(3,4) # random

array([[0.65833018, 0.76371643, 0.90583051, 0.60979769],
       [0.40230251, 0.61581795, 0.36163267, 0.63302767],
       [0.37037728, 0.93479915, 0.50641875, 0.67485719]])

In [92]:
np.random.randint(1,110,(3,3))

array([[49, 36, 23],
       [38, 91, 62],
       [69, 34, 72]])

In [93]:
arr = np.random.rand(3,4)

In [94]:
arr

array([[0.61021005, 0.54171308, 0.49814362, 0.13063605],
       [0.10164181, 0.147748  , 0.95580254, 0.20817327],
       [0.73786601, 0.57489075, 0.4500356 , 0.50568528]])

# Reshaping n*m matrix

In [98]:
arr.reshape(2,6)

array([[0.61021005, 0.54171308, 0.49814362, 0.13063605, 0.10164181,
        0.147748  ],
       [0.95580254, 0.20817327, 0.73786601, 0.57489075, 0.4500356 ,
        0.50568528]])

In [101]:
arr.reshape(6,-6394)

array([[0.61021005, 0.54171308],
       [0.49814362, 0.13063605],
       [0.10164181, 0.147748  ],
       [0.95580254, 0.20817327],
       [0.73786601, 0.57489075],
       [0.4500356 , 0.50568528]])

In [111]:
arr

array([[0.61021005, 0.54171308, 0.49814362, 0.13063605],
       [0.10164181, 0.147748  , 0.95580254, 0.20817327],
       [0.73786601, 0.57489075, 0.4500356 , 0.50568528]])

In [110]:
arr[1:3,1:3]

array([[0.147748  , 0.95580254],
       [0.57489075, 0.4500356 ]])

In [120]:
arr = np.random.randint(1,100,(5,5))

In [128]:
arr

array([[84, 33, 24, 54, 54],
       [66, 44, 35, 35, 85],
       [53,  2, 96,  2, 74],
       [20, 72, 80, 94, 35],
       [51, 66,  1, 29, 48]])

# Applying conditonn

In [122]:
arr[arr>50]

array([84, 54, 54, 66, 85, 53, 96, 74, 72, 80, 94, 51, 66])

In [127]:
arr[1:4,[1,4]]

array([[44, 85],
       [ 2, 74],
       [72, 35]])

# Operations in Array

In [4]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [5]:
arr1

array([[4, 6, 2],
       [4, 7, 5],
       [1, 2, 2]])

In [6]:
arr2

array([[4, 5, 1],
       [6, 5, 4],
       [8, 7, 9]])

In [7]:
arr1+arr2

array([[ 8, 11,  3],
       [10, 12,  9],
       [ 9,  9, 11]])

In [8]:
arr1*arr2

array([[16, 30,  2],
       [24, 35, 20],
       [ 8, 14, 18]])

In [9]:
arr1@arr2

array([[68, 64, 46],
       [98, 90, 77],
       [32, 29, 27]])

In [10]:
arr1/0

C:\Users\Asus\AppData\Local\Temp/ipykernel_2176/1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [11]:
arr1+100

array([[104, 106, 102],
       [104, 107, 105],
       [101, 102, 102]])

# Broad casting in numpy

In [12]:
arr = np.zeros((4,4))

In [13]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
row = np.array([1,2,3,4])

In [15]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [17]:
column = np.array([[1,2,3,4]]).T

In [18]:
arr + column

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [19]:
arr1 = np.random.randint(1,4,(3,4))

# Some More Functions

In [21]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356, 1.        ],
       [1.73205081, 1.        , 1.        , 1.73205081]])

In [22]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183, 20.08553692]])

In [23]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.        , 0.        ],
       [0.        , 0.30103   , 0.30103   , 0.        ],
       [0.47712125, 0.        , 0.        , 0.47712125]])