In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[7, 6, 5, 1],
       [2, 6, 4, 1],
       [5, 9, 7, 4]])

# Reshaping array

In [4]:
arr.reshape(6,2)

array([[7, 6],
       [5, 1],
       [2, 6],
       [4, 1],
       [5, 9],
       [7, 4]])

# Transposing array

In [6]:
arr.T

array([[7, 2, 5],
       [6, 6, 9],
       [5, 4, 7],
       [1, 1, 4]])

In [7]:
arr

array([[7, 6, 5, 1],
       [2, 6, 4, 1],
       [5, 9, 7, 4]])

# Convert to One dimension

In [10]:
arr.flatten()

array([7, 6, 5, 1, 2, 6, 4, 1, 5, 9, 7, 4])

# Expanding array

In [15]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [16]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Squeeze

In [19]:
data = np.array([[1],[2],[3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Repeating Array

In [27]:
arr.repeat(3)

array([7, 7, 7, 6, 6, 6, 5, 5, 5, 1, 1, 1, 2, 2, 2, 6, 6, 6, 4, 4, 4, 1,
       1, 1, 5, 5, 5, 9, 9, 9, 7, 7, 7, 4, 4, 4])

# Rolliing array

In [28]:
np.roll(arr1,2)

array([8, 9, 1, 2, 3, 4, 5, 6, 7])

# Diagonal

In [30]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [31]:
# Numpy Binary Operations

In [33]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [34]:
arr1

array([[7, 1, 4, 1],
       [1, 8, 6, 8],
       [7, 7, 3, 2]])

In [35]:
arr2

array([[4, 7, 3, 5],
       [3, 2, 7, 5],
       [6, 5, 8, 7]])

In [37]:
arr1 & arr2

array([[4, 1, 0, 1],
       [1, 0, 6, 0],
       [6, 5, 0, 2]], dtype=int32)

In [38]:
~arr1

array([[-8, -2, -5, -2],
       [-2, -9, -7, -9],
       [-8, -8, -4, -3]], dtype=int32)

In [39]:
arr1|arr2

array([[ 7,  7,  7,  5],
       [ 3, 10,  7, 13],
       [ 7,  7, 11,  7]], dtype=int32)

In [40]:
arr1>arr2

array([[ True, False,  True, False],
       [False,  True, False,  True],
       [ True,  True, False, False]])

# Numpy string functions

In [42]:
arr = np.array(['TMR','Mit'])

In [43]:
np.char.upper(arr)

array(['TMR', 'MIT'], dtype='<U3')

In [44]:
np.char.title(arr)

array(['Tmr', 'Mit'], dtype='<U3')

In [47]:
np.char.center(arr,10,' ')

array(['   TMR    ', '   Mit    '], dtype='<U10')

# Numpy Mathematical Function

In [48]:
np.sin(arr1)

array([[ 0.6569866 ,  0.84147098, -0.7568025 ,  0.84147098],
       [ 0.84147098,  0.98935825, -0.2794155 ,  0.98935825],
       [ 0.6569866 ,  0.6569866 ,  0.14112001,  0.90929743]])

In [49]:
np.power(arr1,2)

array([[49,  1, 16,  1],
       [ 1, 64, 36, 64],
       [49, 49,  9,  4]], dtype=int32)

In [50]:
np.mean(arr1)

4.583333333333333

In [53]:
np.median(arr1)

5.0

In [54]:
np.std(arr1)

2.752524094152291

In [55]:
np.var(arr1)

7.576388888888889

In [57]:
np.min(arr1)

1

In [58]:
np.max(arr1)

8