In [1]:
import numpy as np 

In [3]:
arr = np.array([1,2,22,3,4,55,6,6,7,7,8,8,8])

In [4]:
arr

array([ 1,  2, 22,  3,  4, 55,  6,  6,  7,  7,  8,  8,  8])

In [5]:
np.sort(arr)

array([ 1,  2,  3,  4,  6,  6,  7,  7,  8,  8,  8, 22, 55])

In [6]:
np.searchsorted(arr,32)

13

In [8]:
arr = np.array([1,2,22,3,4,55,6,6,0,0,7,7,8,8,8])

In [10]:
np.count_nonzero(arr)

13

In [11]:
np.where(arr>6)

(array([ 2,  5, 10, 11, 12, 13, 14], dtype=int32),)

In [12]:
np.extract(arr>3,arr)

array([22,  4, 55,  6,  6,  7,  7,  8,  8,  8])

# Numpy Byte Swapping

In [15]:
arr.byteswap()

array([ 16777216,  33554432, 369098752,  50331648,  67108864, 922746880,
       100663296, 100663296,         0,         0, 117440512, 117440512,
       134217728, 134217728, 134217728])

# Copies and Views 

In [16]:
arr

array([ 1,  2, 22,  3,  4, 55,  6,  6,  0,  0,  7,  7,  8,  8,  8])

In [17]:
arr2 = np.copy(arr) # Deep copy

In [18]:
arr2

array([ 1,  2, 22,  3,  4, 55,  6,  6,  0,  0,  7,  7,  8,  8,  8])

In [19]:
arr3 = arr.view() # shallow copy

# Matrix library

In [20]:
import numpy.matlib as nm

In [21]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Numpy Linear Algebra

In [31]:
arr1 = np.random.randint(1,10,[2,2])
arr2 = np.random.randint(1,10,[2,2])

In [32]:
np.dot(arr1,arr2)

array([[68, 56],
       [73, 77]])

In [33]:
arr1@arr2

array([[68, 56],
       [73, 77]])